### ISSUE TITLE
No software / datasheet for this device

### ISSUE THREAD

**Issue by natbon** [gabrielgbs97/hhc_n8i8op_mqtt#1]
Hi,
I just received the HHC-N8I8OP relay controller, but no configuration tool was supplied.
Your software looks very interesting but I can't configure my device in UDP and thus I can't make it work. How do you configure it ?
Could you please give me a little help ?
Thank you.
NB

**Comment by gabrielgbs97** [comment]
Vendor should provide you the software. Here you have a copy: 

[HHC-N8I8OP-ENGLISH.zip](https://github.com/gabrielgbs97/hhc_n8i8op_mqtt/files/5618828/HHC-N8I8OP-ENGLISH.zip)
Source code of these tools is bundled but github has a limitation of 10MB so I removed them.

**Comment by gabrielgbs97** [comment]
Vendor should provide you the software. Here you have a copy: 

[HHC-N8I8OP-ENGLISH.zip](https://github.com/gabrielgbs97/hhc_n8i8op_mqtt/files/5618828/HHC-N8I8OP-ENGLISH.zip)
Source code these tools is bundled but github has a limitation of 10MB so I removed them.

**Comment by natbon** [comment]
> Vendor should provide you the software. Here you have a copy:
> 
> [HHC-N8I8OP-ENGLISH.zip](https://github.com/gabrielgbs97/hhc_n8i8op_mqtt/files/5618828/HHC-N8I8OP-ENGLISH.zip)
> Source code these tools is bundled but github has a limitation of 10MB so I removed them.

THANK YOU !!!
Vendor DID NOT provide the software. Where am I supposed to find it ?
Please could you send me the WHOLE zip ? With source code too ...
In order to fix the 10Mb limit, you can use wetransfer.com, or framadrop.org, or dl.free.fr
Thanks a lot ...
