### ISSUE TITLE
Configuration software?

### ISSUE THREAD

**Issue by depeter** [gabrielgbs97/hhc_n8i8op_mqtt#2]
Hi,

Sorry this isn't really an issue with your code, I will have to test it still. I can't because I can't seem to find the software for this relay controller anywhere. Vendor's don't reply or send me to a site that is not working (pan.baidu.com). I was hoping you have it and could maybe add it to your repository?

In any case sorry for bothering you with this.

Kind regards,
Peter

**Comment by depeter** [comment]
Ok good news, after thorough internet searching I found it on a forum somewhere. 

https://drive.google.com/file/d/10iwFOBayLvUjvynfSikBjnxMdYFH9vqP/view

**Comment by gabrielgbs97** [comment]
I have [uploaded](https://github.com/gabrielgbs97/hhc_n8i8op_mqtt/commit/bd43f50d846c473bfa598acba68bcf0cbdf2a8a5) the configuration tool, but could not put all files (full zip is 46Mb). Main executables are there.
